# Generated by Django 4.2.6 on 2023-10-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isPreEvento',
            field=models.IntegerField(null=True),
        ),
    ]
