# Generated by Django 4.2.6 on 2023-10-09 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractors',
            fields=[
                ('idContractor', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'contractors',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('idEvent', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=202, null=True)),
                ('date', models.DateTimeField()),
                ('city', models.CharField(max_length=45)),
                ('place', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='EventCategories',
            fields=[
                ('idEventCategorie', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'eventCategories',
            },
        ),
        migrations.CreateModel(
            name='Organizers',
            fields=[
                ('idOrganizers', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'organizers',
            },
        ),
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('idSpecialty', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=77, null=True)),
            ],
            options={
                'db_table': 'specialties',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=101, null=True)),
                ('surnames', models.CharField(max_length=101, null=True)),
                ('email', models.CharField(max_length=101)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='PreEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idContractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.contractors')),
                ('idOrganizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.organizers')),
            ],
            options={
                'db_table': 'preEventos',
            },
        ),
        migrations.AddField(
            model_name='organizers',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.users'),
        ),
        migrations.CreateModel(
            name='OrganizerRatings',
            fields=[
                ('idOrganizerRatings', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(null=True)),
                ('comment', models.CharField(max_length=202, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('idContractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.contractors')),
                ('idOrganizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.organizers')),
            ],
            options={
                'db_table': 'organizerRatings',
            },
        ),
        migrations.CreateModel(
            name='FavoriteOrganizers',
            fields=[
                ('idFavoriteOrganizer', models.AutoField(primary_key=True, serialize=False)),
                ('idOrganizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.organizers')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.users')),
            ],
            options={
                'db_table': 'favoriteOrganizers',
            },
        ),
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('idEvenImage', models.AutoField(primary_key=True, serialize=False)),
                ('urlImage', models.CharField(max_length=404)),
                ('name', models.CharField(max_length=101)),
                ('idEven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.event')),
            ],
            options={
                'db_table': 'eventImages',
            },
        ),
        migrations.CreateModel(
            name='EventFigures',
            fields=[
                ('idEventFigure', models.AutoField(primary_key=True, serialize=False)),
                ('nikname', models.CharField(max_length=45)),
                ('caracteristica', models.CharField(max_length=45, null=True)),
                ('idEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.event')),
            ],
            options={
                'db_table': 'eventFigures',
            },
        ),
        migrations.CreateModel(
            name='Event_eventCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.event')),
                ('idEventCategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.eventcategories')),
            ],
            options={
                'db_table': 'event_eventCategories',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.users'),
        ),
        migrations.CreateModel(
            name='EspecialidadesDeOrganizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idOrganizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.organizers')),
                ('idSpecialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.specialties')),
            ],
            options={
                'db_table': 'especialidadesDeOrganizador',
            },
        ),
        migrations.AddField(
            model_name='contractors',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.users'),
        ),
    ]
