# Generated by Django 4.2.6 on 2023-10-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_contractors_event_eventcategories_organizers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='descripcion',
            field=models.CharField(max_length=808, null=True),
        ),
        migrations.AlterField(
            model_name='organizers',
            name='description',
            field=models.CharField(max_length=808),
        ),
    ]
