# Generated by Django 4.2.6 on 2023-11-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_event_image_event_ispreevento_space_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='like',
            field=models.IntegerField(null=True),
        ),
    ]
