# Generated by Django 4.2.6 on 2023-11-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_event_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='like',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
