# Generated by Django 4.2.6 on 2023-10-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_contractors_iduser_alter_event_iduser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizers',
            name='description',
            field=models.CharField(max_length=202, null=True),
        ),
    ]
