# Generated by Django 4.2.5 on 2023-10-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_organizers_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
