# Generated by Django 4.2.5 on 2023-10-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
