# Generated by Django 4.2.6 on 2023-11-13 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0004_alter_event_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='like',
        ),
        migrations.CreateModel(
            name='eventLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=0, null=True)),
                ('idEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.event')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
