# Generated by Django 4.2.6 on 2023-11-13 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_remove_event_like_eventlikes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventlikes',
            table='eventLikes',
        ),
    ]
