# Generated by Django 4.2.6 on 2023-11-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_event_image'),
        ('mainApp', '0006_alter_eventlikes_table'),
    ]

    operations = [
    ]
