# Generated by Django 4.2.6 on 2023-11-13 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_eventlikes_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizerratings',
            name='idContractor',
        ),
    ]
