# Generated by Django 4.2.7 on 2023-11-14 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_alter_space_image'),
        ('mainApp', '0007_remove_organizerratings_idcontractor'),
    ]

    operations = [
    ]
